#SPDX-License-Identifier: MIT-0
---
- name: Update système (RedHat/Rocky)
  when: ansible_os_family == 'RedHat'
  ansible.builtin.yum:
    name: "*"
    state: latest

- name: Update système (Debian/Ubuntu)
  when: ansible_os_family == 'Debian'
  ansible.builtin.apt:
    update_cache: yes
    upgrade: dist

- name: Installer git et curl
  package:
    name:
      - git
      - curl
    state: present

- name: Ajouter le dépôt NodeSource
  shell: curl -fsSL https://rpm.nodesource.com/setup_23.x | bash -
  args:
    executable: /bin/bash

- name: Installer Node.js
  package:
    name: nodejs
    state: present

- name: Cloner le dépôt quiz-ansible
  git:
    repo: https://github.com/franklin-tutorials/quiz-ansible.git
    dest: /opt/quiz-ansible

- name: Installer les dépendances du projet
  shell: |
    npm install
    npm run build
    npm install -g serve
  args:
    chdir: /opt/quiz-ansible

- name: Lancer l'application avec "serve"
  shell: serve -s dist &
  args:
    chdir: /opt/quiz-ansible
